#!/bin/bash
# Massive Network Game Object Server
# Monitoring Script

pid=`ps ax | awk '($5 ~ /QuadCore-worldd/) { print $1 }'`
cpu=`top -b -n 1 -p $pid | awk '($12 ~ /QuadCore-worldd/) { print $9 }'`
#echo $pid
#echo $cpu
intcpu=${cpu%.*}
#echo $intcpu
if [ "$intcpu" -gt "95" ]
then
	kill -9 $pid
	echo "Killed QuadCore for exceeding it's cpu limit."
	echo `date` ", Killed QuadCore for $intcpu% CPU Usage." >> serverlog
else
	echo "QuadCore Passes the cpu test."
fi
