#!/bin/bash
# Quad Server
# autorestart Script

while :
do
	echo "QuadCore daemon restarted"
	echo `date` >> crash.log &
	./quadcore | tail -n 20 >> crash.log
	echo " " >> crash.log &
	pid=`ps ax | awk '($5 ~ /quadcore/) { print $1 }'`
	wait $pid
        echo `date` ", QuadCore daemon crashed and restarted." >> serverlog
done
